openapi: '3.0.0'

info:
  description: Keep Your kid safe from the internet.
  version: '1.0'
  title: WatchMyKid API

servers:
  - url: http://localhost:8081
    description: Localhost endpoint.

tags:
  - name: user
    description: endpoint for managing user options.
  - name: manage
    description: endpoint to check if some content is correct for kids



paths:
  /user:
    get:
      tags:
        - user
      summary: Retrieve user Information
      description: Invoke this endpoint to retrieve information of a given user.
      operationId: src.api.help.get
      parameters:
        - name: user_id
          in: query
          description: Specifies the user to retrieve.
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Standard WatchMyKid API JSON response. You should check the `error` attribute to determine if there was an error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponse'
        default:
          description: Unexpected error.
          content:
            application/text:
              schema:
                type: string
                description: Error description.
  /manage:
    post:
      tags:
        - manage
      summary: Checks if a webpage is correct for kids
      description: Invoke this endpoint to retrieve information of which help a user needs.
      operationId: src.api.help.post
      requestBody:
        required: true
        description: Body wrapper for the request.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PageToCheck"
      responses:
        200:
          description: Standard WatchMyKid API JSON response. You should check the `error` attribute to determine if there was an error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIResponse'
        default:
          description: Unexpected error.
          content:
            application/text:
              schema:
                type: string
                description: Error description.

components:
  schemas:
    APIResponse:
      type: object
      properties:
        error:
          type: boolean
          description: Whether or not the request was successfully processed or not.
        message:
          type: string
          description: Error message if the request was unsuccessful.
        response:
          type: object
          description: Contains the response data if the request was successful.

    PageToCheck:
      type: object
      properties:
        page_html:
          type: string
          description: Page HTML to scrape.
        tlf:
          type: string
          description: Telephone number to inform
        url:
          type: string
          description: Url to check
